# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: xuchengpeng
subtitle: Valar Morghulis. Valar Dohaeris.
description: Valar Morghulis. Valar Dohaeris.
author: xuchengpeng
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://xuchengpeng.com/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# npm install --save hexo-generator-index
# npm install --save hexo-generator-archive
# npm install --save hexo-generator-tag
index_generator:
  path: ''
  per_page: 10
  order_by: -date

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:xuchengpeng/xuchengpeng.github.io.git
  branch: master

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# npm install hexo-symbols-count-time --save
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true

# 参数说明查看 README：https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
# 文章数，0 为全部
  limit: 0
  hub:
# 是否包含文章内容
  content: true






















theme_config:
  # Theme Configuration

  # For example, you want to put your custom styles file
  # outside theme directory in root `source/_data`, set
  # `styles: source/_data/styles.styl`
  custom_file_path:
    # Default paths: layout/_custom/*
    #head: source/_data/head.swig
    #header: source/_data/header.swig
    #sidebar: source/_data/sidebar.swig
  
    # Default path: source/css/_variables/custom.styl
    variables: source/_data/variables.styl
    # Default path: source/css/_mixins/custom.styl
    #mixins: source/_data/mixins.styl
    # Default path: source/css/_custom/custom.styl
    styles: source/_data/styles.styl
  
  # For example, you put your favicons into `hexo-site/source/images` directory.
  # Then need to rename & redefine they on any other names, otherwise icons from Next will rewrite your custom icons in Hexo.
  favicon:
    small: /images/favicon-16x16.ico
    medium: /images/favicon-32x32.ico
    apple_touch_icon: /images/apple-touch-icon.png
    safari_pinned_tab: /images/favicon-logo.svg
  
  footer:
    # -------------------------------------------------------------
    powered:
      # Hexo link (Powered by Hexo).
      enable: false
      # Version info of Hexo after Hexo link (vX.X.X).
      version: true
  
    theme:
      # Theme & scheme info link (Theme - NexT.scheme).
      enable: false
      # Version info of NexT after scheme info (vX.X.X).
      version: true
      # -------------------------------------------------------------
      # Any custom text can be defined here.
      #custom_text: Hosted by <a target="_blank" rel="external nofollow" href="https://pages.coding.me"><b>Coding Pages</b></a>
  
  # When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives).
  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If translate for this menu will find in languages - this translate will be loaded; if not - Key name will be used. Key is case-senstive.
  # Value before `||` delimeter is the target link.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, question icon will be loaded.
  menu:
    home: / || home
    archives: /archives/ || archive
    categories: /categories/ || th
    tags: /tags/ || tags
    留言: /guestbook/ || commenting
    about: /about/ || user
  
  # Schemes
  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini
  
  # Social Links.
  # Usage: `Key: permalink || icon`
  # Key is the link label showing to end users.
  # Value before `||` delimeter is the target permalink.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, globe icon will be loaded.
  social:
    Wuhan, China: https://www.google.com/maps || map-marker
    E-Mail: mailto:xucp@outlook.com || envelope
    GitHub: https://github.com/xuchengpeng || github
    Bitbucket: https://bitbucket.org/xuchengpeng || bitbucket
  
  # Blog rolls
  links_icon: link
  links_title: 友情链接
  #links_layout: block
  links_layout: inline
  links:
    Chuck's Emacs Configuration: http://xuchengpeng.com/emacs.d/
    HarmonyHu: http://harmonyhu.com/
    linode: https://www.linode.com/
    shadowsocks: https://github.com/shadowsocks
    LeanCloud: https://leancloud.cn/
    Travis CI: https://travis-ci.org/
    NexT: https://github.com/theme-next/hexo-theme-next
  
  # Sidebar Avatar
  # in theme directory(source/images): /images/avatar.gif
  # in site  directory(source/uploads): /uploads/avatar.gif
  avatar: /images/bio-photo.jpg
  
  # Table Of Contents in the Sidebar
  toc:
    enable: true
  
    # Automatically add list number to toc.
    number: true
  
    # If true, all words will placed on next lines if header width longer then sidebar width.
    wrap: true
  
  # Creative Commons 4.0 International License.
  # http://creativecommons.org/
  # Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
  creative_commons: by-nc-sa
  #creative_commons:
  
  sidebar:
    # Sidebar Position, available value: left | right (only for Pisces | Gemini).
    position: left
    #position: right
  
    # Sidebar Display, available value (only for Muse | Mist):
    #  - post    expand on posts automatically. Default.
    #  - always  expand for all pages automatically
    #  - hide    expand only when click on the sidebar toggle icon.
    #  - remove  Totally remove sidebar including sidebar toggle.
    display: post
    #display: always
    #display: hide
    #display: remove
  
    # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
    offset: 12
  
    # Back to top in sidebar (only for Pisces | Gemini).
    b2t: false
  
    # Scroll percent label in b2t button.
    scrollpercent: true
  
    # Enable sidebar on narrow view (only for Muse | Mist).
    onmobile: false
  
  # Post meta display settings
  post_meta:
    item_text: true
    created_at: true
    updated_at:
      enabled: false
      # If true, show updated date label only if `updated date` different from 'created date' (post edited in another day than was created).
      # And if post will edited in same day as created, edited time will show in popup title under created time label.
      # If false show anyway, but if post edited in same day, show only edited time.
      another_day: false
    categories: true
  
  # Post wordcount display settings
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: true
    awl: 2
    wpm: 275
  
  # Reward
  #reward_comment: Donate comment here
  wechatpay: /images/wechatpay.jpg
  alipay: /images/alipay.jpg
  #bitcoin: /images/bitcoin.png
  
  # Related popular posts
  # Dependencies: https://github.com/tea3/hexo-related-popular-posts
  related_posts:
    enable: true
    title: # custom header, leave empty to use the default one
    display_in_home: false
    params:
      maxCount: 5
      #PPMixingRate: 0.0
      #isDate: false
      #isImage: false
      #isExcerpt: false
   
  # Declare license on posts
  post_copyright:
    enable: true
    license: <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" rel="external nofollow" target="_blank">CC BY-NC-SA 4.0</a>
  
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright
  # https://github.com/chriskempson/tomorrow-theme
  highlight_theme: night eighties
  
  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  valine:
    enable: true
    appid: 8cGx0mI721mXnuSact0PLKmV-gzGzoHsz # your leancloud application appid
    appkey: eQc0CtLv9s4VTdObz6ux8lVW # your leancloud application appkey
    notify: false # mail notifier , https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: Leave your comments here... # comment box placeholder
    avatar: wavatar # gravatar style
    guest_info: nick,mail,link # custom comment header
    pageSize: 10 # pagination size
  
  # Show number of visitors to each article.
  # You can visit https://leancloud.cn get AppID and AppKey.
  leancloud_visitors:
    enable: true
    app_id: 8cGx0mI721mXnuSact0PLKmV-gzGzoHsz #<app_id>
    app_key: eQc0CtLv9s4VTdObz6ux8lVW #<app_key>
    # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
    security: false
    betterPerformance: false
  
  # NeedMoreShare2
  # Dependencies: https://github.com/theme-next/theme-next-needmoreshare2
  # See: https://github.com/revir/need-more-share2
  # Also see: https://github.com/DzmVasileusky/needShareButton
  # iconStyle: default | box
  # boxForm: horizontal | vertical
  # position: top / middle / bottom + Left / Center / Right
  # networks: Weibo,Wechat,Douban,QQZone,Twitter,Linkedin,Mailto,Reddit,
  #           Delicious,StumbleUpon,Pinterest,Facebook,GooglePlus,Slashdot,
  #           Technorati,Posterous,Tumblr,GoogleBookmarks,Newsvine,
  #           Evernote,Friendfeed,Vkontakte,Odnoklassniki,Mailru
  needmoreshare2:
    enable: true
    postbottom:
      enable: true
      options:
        iconStyle: box
        boxForm: horizontal
        position: bottomCenter
        networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
    float:
      enable: false
      options:
        iconStyle: box
        boxForm: horizontal
        position: middleRight
        networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
  
  # Tencent analytics ID
  tencent_analytics: 64245444
  
  # Local search
  # Dependencies: https://github.com/theme-next/hexo-generator-searchdb
  local_search:
    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # unescape html strings to the readable one
    unescape: false
  
  # Note tag (bs-callout).
  note:
    # Note tag style values:
    #  - simple    bs-callout old alert style. Default.
    #  - modern    bs-callout new (v2-v3) alert style.
    #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
    #  - disabled  disable all CSS styles import of note tag.
    style: flat
    icons: true
    border_radius: 3
    # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
    # Offset also applied to label tag variables. This option can work with disabled note tag.
    light_bg_offset: 0
  
  # Label tag.
  label: true
  
  # Tabs tag.
  tabs:
    enable: true
    transition:
      tabs: true
      labels: true
    border_radius: 0
  
  # Fancybox. There is support for old version 2 and new version 3.
  # Please, choose only any one variant, do not need to install both.
  # For install 2.x: https://github.com/theme-next/theme-next-fancybox
  # For install 3.x: https://github.com/theme-next/theme-next-fancybox3
  fancybox: true
  
  # Progress bar in the top during page loading.
  # Dependencies: https://github.com/theme-next/theme-next-pace
  pace: true
  # Themes list:
  #pace-theme-big-counter
  #pace-theme-bounce
  #pace-theme-barber-shop
  #pace-theme-center-atom
  #pace-theme-center-circle
  #pace-theme-center-radar
  #pace-theme-center-simple
  #pace-theme-corner-indicator
  #pace-theme-fill-left
  #pace-theme-flash
  #pace-theme-loading-bar
  #pace-theme-mac-osx
  #pace-theme-minimal
  # For example
  # pace_theme: pace-theme-center-simple
  pace_theme: pace-theme-flash
  
  # Script Vendors.
  # Set a CDN address for the vendor you want to customize.
  # For example
  #    jquery: https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js
  # Be aware that you should use the same version as internal ones to avoid potential problems.
  # Please use the https protocol of CDN files when you enable https on your site.
  vendors:
    # Internal path prefix. Please do not edit it.
    _internal: lib
  
    # Internal version: 2.1.3
    jquery: https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js
  
    # Internal version: 2.1.5
    # See: http://fancyapps.com/fancybox/
    fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.2.5/dist/jquery.fancybox.js
    fancybox_css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.2.5/dist/jquery.fancybox.css
  
    # Internal version: 1.0.6
    # See: https://github.com/ftlabs/fastclick
    fastclick:
  
    # Internal version: 1.9.7
    # See: https://github.com/tuupola/jquery_lazyload
    lazyload:
  
    # Internal version: 1.2.1
    # See: http://VelocityJS.org
    velocity: https://cdn.jsdelivr.net/npm/velocity-animate@1.5.1/velocity.min.js
  
    # Internal version: 1.2.1
    # See: http://VelocityJS.org
    velocity_ui: https://cdn.jsdelivr.net/npm/velocity-animate@1.5.1/velocity.ui.min.js
  
    # Internal version: 0.7.9
    # See: https://faisalman.github.io/ua-parser-js/
    ua_parser:
  
    # Internal version: 4.6.2
    # See: http://fontawesome.io/
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
  
    # Internal version: 1
    # https://www.algolia.com
    algolia_instant_js:
    algolia_instant_css:
  
    # Internal version: 1.0.2
    # See: https://github.com/HubSpot/pace
    # Or use direct links below:
    # pace: //cdn.bootcss.com/pace/1.0.2/pace.min.js
    # pace_css: //cdn.bootcss.com/pace/1.0.2/themes/blue/pace-theme-flash.min.css
    pace: https://cdn.jsdelivr.net/npm/pace-js@1.0.2/pace.min.js
    pace_css: https://cdn.jsdelivr.net/npm/pace-js@1.0.2/themes/blue/pace-theme-flash.css
  
    # Internal version: 1.0.0
    # https://github.com/hustcc/canvas-nest.js
    canvas_nest:
  
    # three
    three:
  
    # three_waves
    # https://github.com/jjandxa/three_waves
    three_waves:
  
    # three_waves
    # https://github.com/jjandxa/canvas_lines
    canvas_lines:
  
    # three_waves
    # https://github.com/jjandxa/canvas_sphere
    canvas_sphere:
  
    # Internal version: 1.0.0
    # https://github.com/zproo/canvas-ribbon
    canvas_ribbon:
  
    # Internal version: 3.3.0
    # https://github.com/ethantw/Han
    han:
  
    # Internal version: 3.3.0
    # https://github.com/vinta/pangu.js
    pangu:
  
    # needMoreShare2
    # https://github.com/revir/need-more-share2
    needmoreshare2_js: https://cdn.jsdelivr.net/gh/theme-next/theme-next-needmoreshare2@latest/needsharebutton.min.js
    needmoreshare2_css: https://cdn.jsdelivr.net/gh/theme-next/theme-next-needmoreshare2@latest/needsharebutton.min.css
  
    # bookmark
    # Internal version: 1.0.0
    # https://github.com/theme-next/theme-next-bookmark
    bookmark:
    
    # reading_progress
    # Internal version: 1.0
    # https://github.com/theme-next/theme-next-reading-progress
    # Example: https://cdn.jsdelivr.net/gh/theme-next/theme-next-reading-progress@1.1/reading_progress.min.js
    reading_progress:
    
    # valine comment
    # Example: https://cdn.jsdelivr.net/npm/valine@1.1.8/dist/Valine.min.js
    valine: https://cdn.jsdelivr.net/npm/valine@latest/dist/Valine.min.js

